[phases.setup]
nixPkgs = [
    "ffmpeg-full",
    "python311",
    "gcc"
]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py" 