services:
  - type: web
    name: tiktok-bot
    env: python
    buildCommand: ./render-build.sh
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: BOT_TOKEN
        sync: false
    autoDeploy: false 